# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: clang
      addons:
        apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
        packages:
            - clang-3.7
      env: COMPILER=clang++-3.7


before_install:
  - sudo apt-get install -y pkg-config libgdk-pixbuf2.0-dev libgtk-3-dev libgtkmm-3.0-dev
  - sudo add-apt-repository ppa:gnome3-team/gnome3-staging -y
  - sudo add-apt-repository ppa:gnome3-team/gnome3 -y
  - sudo apt-get -qq update
  - sudo apt-get -qq dist-upgrade

script:
  - cd graphics && make main && make test
